# Generated by Django 5.0.6 on 2025-06-27 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CmtArtr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=50, verbose_name="ใบเสร็จที่")),
                ("date", models.DateField(verbose_name="วันที่")),
                ("month", models.CharField(max_length=10, verbose_name="เดือน")),
                ("year", models.CharField(max_length=10, verbose_name="ปี")),
                ("prd", models.CharField(max_length=20, verbose_name="ห้อง")),
                (
                    "room_no_1",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ห้องที่ 1"
                    ),
                ),
                (
                    "room_no_2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ห้องที่ 2"
                    ),
                ),
                ("member_1", models.CharField(max_length=100, verbose_name="สมาชิก 1")),
                (
                    "member_2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="สมาชิก 2"
                    ),
                ),
                ("duedate", models.DateField(verbose_name="ค่าเช่า")),
                (
                    "remark_1",
                    models.TextField(blank=True, null=True, verbose_name="ชำระเงิน"),
                ),
                (
                    "textstamp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เวลาบันทึก"
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลใบเสร็จ",
                "verbose_name_plural": "ข้อมูลใบเสร็จทั้งหมด",
                "db_table": "CMT_ARTR",
                "ordering": ["-timestamp"],
            },
        ),
    ]
