# Generated by Django 5.0.6 on 2025-07-04 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmtartr",
            name="outstanding_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ยอดค้างชำระ"
            ),
        ),
        migrations.AddField(
            model_name="cmtartr",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ยอดชำระแล้ว"
            ),
        ),
        migrations.AddField(
            model_name="cmtartr",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="รวมเงินทั้งสิ้น"
            ),
        ),
        migrations.AddField(
            model_name="cmtartr",
            name="total_before_vat",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="มูลค่าก่อนภาษี"
            ),
        ),
        migrations.AddField(
            model_name="cmtartr",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="เวลาอัพเดท"),
        ),
        migrations.AddField(
            model_name="cmtartr",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ภาษีมูลค่าเพิ่ม"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="bill_no",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="เลขที่ใบแจ้งหนี้"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="duedate",
            field=models.DateField(verbose_name="ชำระภายในวันที่"),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="member_1",
            field=models.CharField(max_length=100, verbose_name="รหัส-ชื่อ 1"),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="member_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="รหัส-ชื่อ 2"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="month",
            field=models.CharField(max_length=10, verbose_name="ประจำเดือน"),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="prd",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="งวด"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="remark_1",
            field=models.TextField(blank=True, null=True, verbose_name="หมายเหตุ 1"),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="room_no_1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เลขที่ห้อง 1"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="room_no_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="เลขที่ห้อง 2"
            ),
        ),
        migrations.AlterField(
            model_name="cmtartr",
            name="textstamp",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="หมายเหตุ 2"
            ),
        ),
        migrations.CreateModel(
            name="CmtArtrItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="หมายเลขแถว")),
                (
                    "item_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="รหัสสินค้า"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="รายการ"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="อัตรา"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="จำนวน"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="เป็นเงิน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เวลาสร้าง"
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_items",
                        to="expense.cmtartr",
                        verbose_name="ใบแจ้งหนี้",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการใบแจ้งหนี้",
                "verbose_name_plural": "รายการใบแจ้งหนี้ทั้งหมด",
                "db_table": "CMT_ARTR_ITEM",
                "ordering": ["row_number"],
                "unique_together": {("bill", "row_number")},
            },
        ),
    ]
