# Generated by Django 5.2.4 on 2025-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_cmtartr_outstanding_amount_cmtartr_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtartritem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='รายงาน'),
        ),
        migrations.AlterField(
            model_name='cmtartritem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส'),
        ),
    ]
