# Generated by Django 5.2.4 on 2025-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_cmtartritem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmtartritem',
            name='bill_no',
            field=models.CharField(default='-', max_length=20, verbose_name='เลขที่บิลล์'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmtartritem',
            name='m_y_prd',
            field=models.CharField(default='-', max_length=20, verbose_name='เดือน/ปี/งวด'),
            preserve_default=False,
        ),
    ]
