# Generated by Django 5.2.4 on 2025-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_cmtartritem_bill_no_cmtartritem_m_y_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtartritem',
            name='bill_no',
            field=models.CharField(default='-', max_length=20, verbose_name='เลขที่บิลล์'),
        ),
        migrations.AlterField(
            model_name='cmtartritem',
            name='m_y_prd',
            field=models.CharField(default='-', max_length=20, verbose_name='เดือน/ปี/งวด'),
        ),
    ]
