# Generated by Django 5.2.4 on 2025-07-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_cmtartritem_bill_no_alter_cmtartritem_m_y_prd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmtartritem',
            unique_together={('row_number',)},
        ),
        migrations.AlterField(
            model_name='cmtartritem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='expense.cmtartr', verbose_name='เลขที่บิลล์'),
        ),
        migrations.RemoveField(
            model_name='cmtartritem',
            name='bill_no',
        ),
    ]
