# Generated by Django 5.2.4 on 2025-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_cmtartritem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmtartritem',
            name='bill',
        ),
        migrations.AddField(
            model_name='cmtartritem',
            name='bill_no',
            field=models.CharField(default='-', max_length=20, verbose_name='เดือน/ปี/งวด'),
        ),
    ]
