# Generated by Django 5.2.4 on 2025-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_remove_cmtartritem_bill_cmtartritem_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmtartritem',
            name='room_no',
            field=models.CharField(default='-', max_length=10, verbose_name='หมายเลขห้อง'),
        ),
        migrations.AlterField(
            model_name='cmtartritem',
            name='bill_no',
            field=models.CharField(default='-', max_length=20, verbose_name='เลขที่บิลล์'),
        ),
    ]
