# Generated by Django 5.2.4 on 2025-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_cmtartritem_room_no_alter_cmtartritem_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmtartritem',
            name='textstamp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ตรวจสอบการชำระบิล'),
        ),
    ]
