# Generated by Django 5.2.4 on 2025-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_cmtartritem_textstamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtartritem',
            name='textstamp',
            field=models.CharField(default='unpaid', max_length=50, verbose_name='ตรวจสอบการชำระบิล'),
        ),
    ]
