# Generated by Django 5.2.5 on 2025-08-27 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmtArtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบแจ้งหนี้')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('month', models.CharField(max_length=10, verbose_name='ประจำเดือน')),
                ('year', models.CharField(max_length=10, verbose_name='ปี')),
                ('prd', models.CharField(blank=True, max_length=20, null=True, verbose_name='งวด')),
                ('room_no_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่ห้อง 1')),
                ('room_no_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่ห้อง 2')),
                ('member_1', models.CharField(max_length=100, verbose_name='รหัส-ชื่อ 1')),
                ('member_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัส-ชื่อ 2')),
                ('duedate', models.DateField(verbose_name='ชำระภายในวันที่')),
                ('remark_1', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ 1')),
                ('textstamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเหตุ 2')),
                ('total_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='มูลค่าก่อนภาษี')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ภาษีมูลค่าเพิ่ม')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รวมเงินทั้งสิ้น')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดชำระแล้ว')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดค้างชำระ')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาบันทึก')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาอัพเดท')),
            ],
            options={
                'verbose_name': 'ข้อมูลใบเสร็จ',
                'verbose_name_plural': 'ข้อมูลใบเสร็จทั้งหมด',
                'db_table': 'CMT_ARTR',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CmtArtrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='หมายเลขแถว')),
                ('room_no', models.CharField(default='-', max_length=10, verbose_name='หมายเลขห้อง')),
                ('m_y_prd', models.CharField(default='-', max_length=20, verbose_name='เดือน/ปี/งวด')),
                ('bill_no', models.CharField(default='-', max_length=20, verbose_name='เลขที่บิลล์')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='รายงาน')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='อัตรา')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวน')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เป็นเงิน')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาสร้าง')),
                ('textstamp', models.CharField(default='unpaid', max_length=50, verbose_name='ตรวจสอบการชำระบิล')),
            ],
            options={
                'verbose_name': 'รายการใบแจ้งหนี้',
                'verbose_name_plural': 'รายการใบแจ้งหนี้ทั้งหมด',
                'db_table': 'CMT_ARTR_ITEM',
                'ordering': ['row_number'],
                'unique_together': {('row_number',)},
            },
        ),
    ]
