# Generated by Django 5.2.5 on 2025-09-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m34', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmtartritem',
            options={'ordering': ['created_at'], 'verbose_name': 'รายการใบแจ้งหนี้', 'verbose_name_plural': 'รายการใบแจ้งหนี้ทั้งหมด'},
        ),
        migrations.AlterUniqueTogether(
            name='cmtartritem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cmtartritem',
            name='row_number',
        ),
    ]
