# Generated by Django 5.2.5 on 2025-09-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m34', '0002_alter_cmtartritem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmtartr',
            name='textstamp',
        ),
        migrations.AddField(
            model_name='cmtartr',
            name='remark_2',
            field=models.CharField(blank=True, null=True, verbose_name='หมายเหตุ 2'),
        ),
    ]
