# Generated by Django 5.2.4 on 2025-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmtRctr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_c_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบเสร็จ')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('payin', models.CharField(verbose_name='ฝาก')),
                ('room_no_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่ห้อง 1')),
                ('room_no_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่ห้อง 2')),
                ('member_1', models.CharField(max_length=100, verbose_name='รหัส-ชื่อ 1')),
                ('member_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='รหัส-ชื่อ 2')),
                ('type', models.CharField(blank=True, choices=[('ชำระตามบิล', 'ชำระตามบิล'), ('จ่ายล่วงหน้า', 'จ่ายล่วงหน้า'), ('รายรับอื่นๆ', 'รายรับอื่นๆ')], max_length=20, null=True, verbose_name='ประเภท')),
                ('payment_method', models.CharField(blank=True, choices=[('เงินสด', 'เงินสด'), ('เช็ค', 'เช็ค'), ('เงินโอน', 'เงินโอน'), ('อื่นๆ', 'อื่นๆ')], max_length=20, null=True, verbose_name='ชำระโดย')),
                ('bank_1', models.CharField(max_length=100, verbose_name='ธนาคาร 1')),
                ('bank_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ธนาคาร 2')),
                ('bank_no', models.CharField(max_length=20, verbose_name='เลขที่')),
                ('bank_date', models.DateField(verbose_name='วันที่(ธนาคาร)')),
                ('vat', models.BooleanField(default=False, verbose_name='ภาษีหักณที่จ่าย')),
                ('deduct_from_prepaid', models.BooleanField(default=False, verbose_name='ลดหนี้จากการชำระล่วงหน้า')),
                ('withdraw_from_bankaccount', models.BooleanField(default=False, verbose_name='ตัดบัญชีเงินฝากส่วนตัว')),
                ('withdraw', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตัดบัญชีเงินฝากส่วนตัว(กรอก)')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='ยอดชำระสุทธิ')),
                ('tax_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่หนังสือรับรองการหักภาษี')),
                ('tax_date', models.DateField(verbose_name='ลงวันที่')),
                ('no_ref', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่อ้างอิง')),
                ('remark_1', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ 1')),
                ('remark_2', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ 2')),
                ('textstamp', models.CharField(blank=True, null=True, verbose_name='textstamp')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='เวลาอัพเดท')),
            ],
            options={
                'verbose_name': 'ใบเสร็จรับเงิน',
                'verbose_name_plural': 'ใบเสร็จรับเงินทั้งหมด',
                'db_table': 'CMT_RCTR',
                'ordering': ['-timestamp'],
            },
        ),
    ]
