# Generated by Django 5.2.4 on 2025-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m35', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtrctr',
            name='payin',
            field=models.DateField(verbose_name='ฝาก'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='room_no_1',
            field=models.CharField(max_length=20, verbose_name='เลขที่ห้อง 1'),
        ),
    ]
