# Generated by Django 5.2.4 on 2025-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m35', '0002_alter_cmtrctr_payin_alter_cmtrctr_room_no_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtrctr',
            name='bank_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ธนาคาร 1'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='bank_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่(ธนาคาร)'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='bank_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='deduct_from_prepaid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ลดหนี้จากการชำระล่วงหน้า'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='tax_date',
            field=models.DateField(blank=True, null=True, verbose_name='ลงวันที่'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='vat',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ภาษีหักณที่จ่าย'),
        ),
        migrations.AlterField(
            model_name='cmtrctr',
            name='withdraw_from_bankaccount',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ตัดบัญชีเงินฝากส่วนตัว'),
        ),
    ]
