# Generated by Django 5.2.4 on 2025-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m35', '0003_alter_cmtrctr_bank_1_alter_cmtrctr_bank_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtrctr',
            name='payin',
            field=models.DateField(blank=True, null=True, verbose_name='ฝาก'),
        ),
    ]
